import { existsSync, mkdirSync, readFileSync, readdirSync, realpathSync, writeFileSync } from 'node:fs';
import { registerHooks } from 'node:module';
import { homedir } from 'node:os';
import { basename, dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { compileWorkflow } from '../workflows.ts';
import {
  WORKFLOWS,
  isShippedWorkflowName,
  validatedWorkflowSpec,
  workflowDefinition,
} from '../registry/workflows.ts';
import type { CompiledWorkflow, WorkflowName, WorkflowSpecInput } from '../registry/workflows.ts';
import type { WorkflowDefinition } from '../registry/define.ts';
import type { WorkflowSource } from '../run/store.ts';

export interface ResolvedWorkflowSource {
  workflow: CompiledWorkflow;
  source: WorkflowSource;
}

export interface WorkflowDirProvisioning {
  dir: string;
  tsconfigPath: string;
  dtsPath: string;
}

export interface DiscoveredWorkflowSources {
  name: string;
  layers: WorkflowSource[];
}

interface CliSelfRef {
  exec: string;
  entry?: string;
}

const WORKFLOW_SDK_SPECIFIER = 'duet/workflows';
const WORKFLOW_DTS_FILE = 'duet-workflows.d.ts';
const WORKFLOW_TSCONFIG_FILE = 'tsconfig.json';

export function projectWorkflowDir(cwd: string): string {
  return join(cwd, '.duet', 'workflows');
}

export function userWorkflowDir(home: string = homedir()): string {
  return join(home, '.config', 'duet', 'workflows');
}

export function formatWorkflowSource(source: WorkflowSource, cwd?: string): string {
  if (source.layer === 'shipped') return 'shipped';
  const path = source.path && cwd ? relative(cwd, source.path) || basename(source.path) : source.path;
  return path ? `${source.layer}: ${path}` : source.layer;
}

function packageRoot(): string {
  const here = fileURLToPath(import.meta.url);
  const fromSource = join(dirname(here), '..', '..', 'package.json');
  if (existsSync(fromSource)) return dirname(fromSource);
  const fromDist = join(dirname(here), '..', 'package.json');
  return dirname(fromDist);
}

function duetVersion(): string {
  try {
    return (JSON.parse(readFileSync(join(packageRoot(), 'package.json'), 'utf8')) as { version?: string }).version ?? '0.0.0';
  } catch {
    return '0.0.0';
  }
}

function realish(path: string): string {
  try {
    return realpathSync(path);
  } catch {
    return resolve(path);
  }
}

function currentSelfRef(): CliSelfRef {
  return { exec: process.execPath, ...(process.argv[1] ? { entry: process.argv[1] } : {}) };
}

export function workflowSdkRuntimeUrl(
  self: CliSelfRef = currentSelfRef(),
  moduleUrl: string = import.meta.url,
): string {
  void self.exec;
  const candidates: string[] = [];
  if (self.entry) {
    const entry = realish(self.entry);
    if (entry.endsWith(join('src', 'surfaces', 'cli.ts'))) candidates.push(resolve(dirname(entry), '..', 'workflows.ts'));
    candidates.push(join(dirname(entry), 'workflows.mjs'));
  }

  const here = fileURLToPath(moduleUrl);
  if (here.endsWith(join('src', 'surfaces', 'workflow-source.ts'))) candidates.push(resolve(dirname(here), '..', 'workflows.ts'));
  candidates.push(join(dirname(here), 'workflows.mjs'));

  const target = candidates.find((candidate) => existsSync(candidate)) ?? candidates[0];
  if (!target) throw new Error(`could not resolve ${WORKFLOW_SDK_SPECIFIER} from duet's CLI entry`);
  return pathToFileURL(target).href;
}

function workflowDts(): string {
  return `// Generated by duet ${duetVersion()} for workflow authoring. Do not edit.
declare module '${WORKFLOW_SDK_SPECIFIER}' {
  export type GateName = string;
  export type ArtifactKind = 'spec' | 'plan' | 'design';
  export type ReviewPosture = 'critique' | 'writable' | 'fixer';

  export interface WorkflowDefinitionInput {
    readonly name: string;
    readonly title: string;
    readonly phases: readonly PhaseExpr[];
    readonly attend?: readonly GateName[];
    readonly presets?: Record<string, readonly GateName[]>;
  }

  export interface WorkflowDefinition extends WorkflowDefinitionInput {}
  export interface CompiledWorkflow {
    readonly name: string;
    readonly displayName: string;
  }

  export type PhaseExpr =
    | { readonly block: 'frame'; readonly name?: string }
    | { readonly block: 'doc'; readonly artifact: ArtifactKind; readonly rounds?: number; readonly contract?: boolean; readonly audit?: boolean; readonly name?: string }
    | { readonly block: 'build'; readonly review: ReviewPosture; readonly audit?: boolean; readonly name?: string }
    | { readonly block: 'finish'; readonly name?: string };

  export function frame(options?: { readonly name?: string }): PhaseExpr;
  export function doc(artifact: ArtifactKind, options?: { readonly rounds?: number; readonly contract?: boolean; readonly audit?: boolean; readonly name?: string }): PhaseExpr;
  export function build(options: { readonly review: ReviewPosture; readonly audit?: boolean; readonly name?: string }): PhaseExpr;
  export function finish(options?: { readonly name?: string }): PhaseExpr;
  export function defineWorkflow(input: WorkflowDefinitionInput): WorkflowDefinition;
  export function compileWorkflow(definition: WorkflowDefinition): CompiledWorkflow;
}
`;
}

function workflowTsconfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: 'ESNext',
        module: 'ESNext',
        moduleResolution: 'Bundler',
        strict: true,
        allowImportingTsExtensions: true,
        erasableSyntaxOnly: true,
        verbatimModuleSyntax: true,
        noEmit: true,
        paths: { [WORKFLOW_SDK_SPECIFIER]: [`./${WORKFLOW_DTS_FILE}`] },
        skipLibCheck: true,
      },
      include: ['*.ts', WORKFLOW_DTS_FILE],
    },
    null,
    2,
  )}\n`;
}

export function provisionWorkflowDir(dir: string): WorkflowDirProvisioning {
  mkdirSync(dir, { recursive: true });
  const tsconfigPath = join(dir, WORKFLOW_TSCONFIG_FILE);
  if (!existsSync(tsconfigPath)) writeFileSync(tsconfigPath, workflowTsconfig());
  const dtsPath = join(dir, WORKFLOW_DTS_FILE);
  const next = workflowDts();
  const current = existsSync(dtsPath) ? readFileSync(dtsPath, 'utf8') : undefined;
  if (current !== next) writeFileSync(dtsPath, next);
  return { dir, tsconfigPath, dtsPath };
}

let workflowHookRegistered = false;

function registerWorkflowResolveHook(): void {
  if (workflowHookRegistered) return;
  const sdkUrl = workflowSdkRuntimeUrl();
  registerHooks({
    resolve(specifier, context, nextResolve) {
      if (specifier === WORKFLOW_SDK_SPECIFIER) return { url: sdkUrl, shortCircuit: true };
      return nextResolve(specifier, context);
    },
  });
  workflowHookRegistered = true;
}

function isWorkflowDefinitionFileName(file: string): boolean {
  return file.endsWith('.ts') && !file.endsWith('.d.ts');
}

function workflowNameFromDefinitionFile(file: string): string {
  return file.slice(0, -'.ts'.length);
}

function tsNames(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && isWorkflowDefinitionFileName(entry.name))
    .map((entry) => workflowNameFromDefinitionFile(entry.name))
    .sort();
}

function candidateFile(dir: string, name: string): string | undefined {
  if (!isWorkflowDefinitionFileName(`${name}.ts`)) return undefined;
  const path = join(dir, `${name}.ts`);
  return existsSync(path) ? path : undefined;
}

function candidateLayersFor(name: string, projectDir: string, userDir: string): WorkflowSource[] {
  const candidates: WorkflowSource[] = [];
  if (isShippedWorkflowName(name)) candidates.push({ layer: 'shipped' });
  const projectPath = candidateFile(projectDir, name);
  if (projectPath) candidates.push({ layer: 'project', path: projectPath });
  const userPath = candidateFile(userDir, name);
  if (userPath) candidates.push({ layer: 'user', path: userPath });
  return candidates;
}

export function definedWorkflowSources(cwd: string, name: string, opts: { home?: string } = {}): WorkflowSource[] {
  return candidateLayersFor(name, projectWorkflowDir(cwd), userWorkflowDir(opts.home));
}

export function discoverWorkflowSources(cwd: string, opts: { home?: string } = {}): DiscoveredWorkflowSources[] {
  const projectDir = projectWorkflowDir(cwd);
  const userDir = userWorkflowDir(opts.home);
  const names = new Set([...Object.keys(WORKFLOWS), ...tsNames(projectDir), ...tsNames(userDir)]);
  return [...names]
    .sort()
    .map((name) => ({ name, layers: candidateLayersFor(name, projectDir, userDir) }));
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function isCompiledLike(value: unknown): value is WorkflowSpecInput {
  return isRecord(value) && typeof value.name === 'string' && typeof value.displayName === 'string' && Array.isArray(value.phases);
}

function moduleWorkflowExport(mod: Record<string, unknown>, path: string): unknown {
  if ('default' in mod) return mod.default;
  if ('workflow' in mod) return mod.workflow;
  throw new Error(
    `${path} does not export a workflow definition — default-export defineWorkflow({ ... }) from this file.`,
  );
}

async function loadWorkflowFile(path: string, requestedName: string): Promise<CompiledWorkflow> {
  let mod: Record<string, unknown>;
  try {
    registerWorkflowResolveHook();
    mod = (await import(pathToFileURL(path).href)) as Record<string, unknown>;
  } catch (err) {
    throw new Error(`${path} could not be imported (${err instanceof Error ? err.message : String(err)}) — fix or remove the workflow file.`);
  }
  const exported = moduleWorkflowExport(mod, path);
  const workflow = isCompiledLike(exported)
    ? validatedWorkflowSpec(exported)
    : compileWorkflow(exported as WorkflowDefinition);
  if (workflow.name !== requestedName) {
    throw new Error(
      `${path} exports workflow "${workflow.name}" but was loaded as "${requestedName}" — rename the file or the defineWorkflow({ name }) value so they match.`,
    );
  }
  return workflow;
}

export async function resolveWorkflowSource(
  cwd: string,
  name: WorkflowName,
  opts: { home?: string } = {},
): Promise<ResolvedWorkflowSource> {
  const projectDir = projectWorkflowDir(cwd);
  const userDir = userWorkflowDir(opts.home);
  if (existsSync(projectDir)) provisionWorkflowDir(projectDir);
  if (existsSync(userDir)) provisionWorkflowDir(userDir);
  const candidateSources = candidateLayersFor(name, projectDir, userDir);

  if (candidateSources.length > 1) {
    throw new Error(
      `workflow "${name}" is defined in multiple layers (${candidateSources.map((source) => formatWorkflowSource(source, cwd)).join(', ')}) — remove the duplicate; duet rejects workflow shadowing rather than choosing a winner.`,
    );
  }
  if (candidateSources.length === 0) {
    const project = tsNames(projectDir);
    const user = tsNames(userDir);
    const available = [
      `shipped: ${Object.keys(WORKFLOWS).join(', ')}`,
      ...(project.length > 0 ? [`project: ${project.join(', ')}`] : []),
      ...(user.length > 0 ? [`user: ${user.join(', ')}`] : []),
    ].join(' · ');
    throw new Error(
      `workflow "${name}" was not found — choose one of ${available}, or add ${name}.ts under ${projectDir} or ${userDir}.`,
    );
  }

  const [source] = candidateSources;
  if (source!.layer === 'shipped') {
    return { workflow: validatedWorkflowSpec(workflowDefinition(name)), source: source! };
  }
  return { workflow: await loadWorkflowFile(source!.path!, name), source: source! };
}
